[
    {
        "nr": "1",
        "articleid": "1234",
        "articletype": "beer",
        "name": "Guinness Draught",
        "priceinclvat": "3.99",
        "volumeml": 440,
        "priceperlitre": 9.07,
        "introduced": "1994",
        "finaldelivery": "2023-12-31",
        "category": "Stout",
        "packaging": "Bottle",
        "captype": "Screw Cap",
        "country": "Ireland",
        "producer": "Guinness Brewery",
        "provider": "Tesco",
        "productionyear": "2023",
        "testedproductionyear": "2023",
        "alcoholstrength": "4.2%",
        "module": "6",
        "assortment": "Regular",
        "organic": 0,
        "kosher": 0
    },
    {
        "nr": "2",
        "articleid": "5678",
        "articletype": "beer",
        "name": "Heineken Lager",
        "priceinclvat": "2.49",
        "volumeml": 330,
        "priceperlitre": 7.55,
        "introduced": "1864",
        "finaldelivery": "2023-12-31",
        "category": "Lager",
        "packaging": "Can",
        "captype": "Pull Tab",
        "country": "Netherlands",
        "producer": "Heineken International",
        "provider": "Asda",
        "productionyear": "2023",
        "testedproductionyear": "2023",
        "alcoholstrength": "5.0%",
        "module": "6",
        "assortment": "Regular",
        "organic": 0,
        "kosher": 1
    },
    {
        "nr": "3",
        "articleid": "91011",
        "articletype": "beer",
        "name": "Sierra Nevada Pale Ale",
        "priceinclvat": "4.75",
        "volumeml": 355,
        "priceperlitre": 13.38,
        "introduced": "1980",
        "finaldelivery": "2023-12-31",
        "category": "American Pale Ale",
        "packaging": "Bottle",
        "captype": "Cork",
        "country": "United States",
        "producer": "Sierra Nevada Brewing Co.",
        "provider": "Waitrose",
        "productionyear": "2023",
        "testedproductionyear": "2023",
        "alcoholstrength": "5.6%",
        "module": "6",
        "assortment": "Regular",
        "organic": 1,
        "kosher": 0
    },
    {
        "nr": "4",
        "articleid": "121314",
        "articletype": "beer",
        "name": "Chimay Blue",
        "priceinclvat": "6.99",
        "volumeml": 330,
        "priceperlitre": 21.18,
        "introduced": "1956",
        "finaldelivery": "2023-12-31",
        "category": "Trappist Ale",
        "packaging": "Bottle",
        "captype": "Cork",
        "country": "Belgium",
        "producer": "Chimay Brewery",
        "provider": "Sainsbury's",
        "productionyear": "2023",
        "testedproductionyear": "2023",
        "alcoholstrength": "9.0%",
        "module": "6",
        "assortment": "Regular",
        "organic": 0,
        "kosher": 0
    },
    {
        "nr": "5",
        "articleid": "151617",
        "articletype": "beer",
        "name": "Paulaner Hefe-Weissbier",
        "priceinclvat": "3.25",
        "volumeml": 500,
        "priceperlitre": 6.50,
        "introduced": "1634",
        "finaldelivery": "2023-12-31",
        "category": "Wheat Beer",
        "packaging": "Bottle",
        "captype": "Screw Cap",
        "country": "Germany",
        "producer": "Paulaner Brewery",
        "provider": "Morrisons",
        "productionyear": "2023",
        "testedproductionyear": "2023",
        "alcoholstrength": "5.5%",
        "module": "6",
        "assortment": "Regular",
        "organic": 0,
        "kosher": 1
    }
]
  